logging:
    level:
        com:
            zaxxer:
                hikari: DEBUG
        org:
            springframework: DEBUG
server:
    port: 8082
spring:
    application:
        name: engine
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${JAMIFY_UAA_BASE_URL}

security:
    jwt:
        public-key: public.pem

gateway:
    url: http://jamify.daddyornot.xyz
    service:
        front: /mobile-app

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

config:
    external:
        apis:
            spotify:
                url:
                    base: https://api.spotify.com/v1
            amazon:
                url:
                    base: todo
    uaa:
        url:
            base: ${JAMIFY_UAA_BASE_URL}
            refresh-access-token: ${config.uaa.url.base}/api/v1/auth/refresh-access-token
        jamify-engine-api-key: ${JAMIFY_ENGINE_API_KEY}
    orchestrator:
        url:
            base: http://localhost:8083