logging:
    level:
        com:
            zaxxer:
                hikari: DEBUG
        org:
            springframework: DEBUG
server:
    port: 8082
spring:
    application:
        name: engine
    datasource:
        password: devpwd
        url: jdbc:postgresql://localhost:5432/engine
        username: developer
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${JAMIFY_UAA_BASE_URL}

security:
    jwt:
        public-key: public.pem

gateway:
    url: http://localhost:5173
    service:
        front: /mobile-app

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html

config:
    uaa:
        url:
            base: ${JAMIFY_UAA_BASE_URL}
            refresh-access-token: ${config.uaa.url.base}/api/v1/auth/refresh-access-token
        jamify-engine-api-key: ${JAMIFY_ENGINE_API_KEY}