services:
  postgres-engine:
    container_name: postgres-engine
    image: postgres:16
    environment:
      POSTGRES_DB: engine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 15s
      timeout: 2s
      retries: 15
    ports:
      - "5432:5432"

#  jamify-engine:
#    container_name: jamify-engine
#    build:
#      context: ../
#      dockerfile: Dockerfile
#    ports:
#      - "8082:8082"
#    environment:
#      POSTGRES_HOST: postgres-engine
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: engine
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      JWK_KEY_ID: jamify-uaa-key-id
#      JAMIFY_UAA_BASE_URL: http://jamify.daddyornot.xyz/jamify-uaa
#      JAMIFY_ENGINE_API_KEY: 894daze-daz41eazLwXrrt-55rryrtnbv2-apmqFzf
