name: Build And Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn -B package --file pom.xml -Dspring.profiles.active=test
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact
          path: target/*.jar

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      # - name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

